#########################
#####   InvUnload   #####
#########################

#
# InvUnload has the following commands:
#
# /unload will check if nearby chests contain items you are carrying
# outside of your hotbar. If yes, those will be put into the chest. 
#
# /dump will dump all your inventory contents except your hotbar into
# nearby chests, regardless of what is inside, but it first try
# to /unload them.
#
# /unloadinfo (or /dumpinfo) will show you in which chests your stuff
# went into when you last used /unload or /dump.
#
# Players need the invunload.use permission for all regular commands.
#
# If you have the permission invunload.reload, you can reload the
# config using /unload reload
#

# Players can use /unload <radius> to unload their inventory into matching
# chests that are within that radius. Also applies to /dump <radius>
# Can be overridden for custom groups. See groups.yml
max-chest-radius: 20

# The default radius is used when players use /unload without specifying
# a radius. Also applies to /dump
# Can be overridden for custom groups. See groups.yml
default-chest-radius: 10

#########################
##### Animations   ######
#########################

# InvUnload can spawn particles and play sounds at each affected chest
# so that you can see where your items went.

# List of particle types: https://minecraft.gamepedia.com/Particles#Types_of_particles
# You must check that the specified particle type is valid in your specific Minecraft version!
spawn-particles: true
particle-type: SPELL_WITCH
particle-count: 100

# List of sound effects: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# You must check that the specified sound effect is valid in your specific Minecraft version!
play-sound: true
sound-effect: ENTITY_PLAYER_LEVELUP

##############################
##### Laser and Summary ######
##############################

# Some people wonder in which chests their items went. To get an overview, InvUnload
# can show a laser beam between yourself and the affected chests, and display a text
# summary in the chat. By default, both is triggered by /unloadinfo (or /dumpinfo).
# You can also enable both, the laser and the summary, to be displayed everytime you
# do /unload or /dump.

# When set to true, a text summary is printed in chat everytime the player uses /unload
# or /dump.
# When set to false, the summary is only shown when using /unloadinfo (or /dumpinfo).
always-show-summary: true

# When set to true, InvUnload will draw the laser beam everytime you /unload or /dump
# When set to false, InvUnload only draws the laser beam on /unloadinfo (or /dumpinfo)
laser-animation: false

# How many seconds shall the laser be shown?
# If you use /unloadinfo, you can override this value with /unloadinfo [duration]
laser-default-duration: 10

# Maximum time in seconds that is allowed when using /unloadingo [duration]
laser-max-duration: 30

# Disable the laser once the player is this many blocks away
laser-max-distance: 50

# You can have the laser move with the player to get even better information on
# where your stuff went to.
laser-moves-with-player: true

##############################
##### 3rd party plugins ######
##############################

##### Protection plugins #####
# When enabled, InvUnload will call a PlayerInteractEvent upon unloading
# or dump attempts to check if the player is allowed to use this chest.
# If you don't know what this means, don't this config.
use-playerinteractevent: true

##### ChestSort #####
# When enabled, InvUnload will automatically use ChestSort
# to sort every chest that has been affected by unloading/dumping
# if the player has automatic sorting enabled.
# This will only work if ChestSort (www.chestsort.de) is installed.
use-chestsort: true

##### PlotSquared #####
# When enabled, InvUnload will check if you are using PlotSquared.
# Players will then only be able to unload into chests that are
# in their own plots and in plots that match the settings below
use-plotsquared: true

# Allows players to unload into chests that are in foreign Plots if
# the players is a trusted member of that plot
plotsquared-allow-when-trusted: true

# Allows players to unload into chests that do not belong to any Plot
plotsquared-allow-outside-plots: true

##########################
##### Update Checker #####
##########################

# Checks for updates (asynchronously).
# When enabled, a message is printed in the console if a new
# version has been found, and OPs will be notified when they join the server 
# When set to true, check for updates on startup and every X hours (see "check-interval" below)
# When set to on-startup, only check on server startup
# When set to false, don't check for updates
check-for-updates: true

# When you set "check-for-updates" to true, you can define the amount
# of hours inbetween each update check.
check-interval: 4

#########################
##### localization ######
#########################

# Available color codes:
# &0 Black        &6 Gold       &c Red
# &1 Dark Blue    &7 Gray       &d Light Purple
# &2 Dark Green   &8 Dark Gray  &e Yellow
# &3 Dark Aqua    &9 Blue       &f White
# &4 Dark Red     &a Green     
# &5 Dark Purple  &b Aqua

# Available formatting codes:
# &k Obfuscated   &m Strikethrough
# &l Bold         &o Italic
# &n Underline    &r Reset

# By default, every message sent by InvUnload has a [InvUnload] prefix.
# You can change this if you want or set it to an empty string to disable it.
message-prefix: "&6[InvUnload] &r"

##### English
message-could-not-unload: "&7Nothing to unload: There are no chests for the remaining items."
message-radius-too-high: "&cError:&7 The radius cannot be higher than %d blocks."
message-no-chests-nearby: "&7Nothing to unload: There are no chests nearby. Adjust the radius or walk closer to your chests."
message-error-not-a-number: "&cError:&7 '%s' is not a valid number."
message-inventory-empty: "&7Nothing to unload: Your inventory is already empty."

##### Chinese (Simplified)
##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-could-not-unload: "&7没有东西可以卸下，也许你没有给其余物品的箱子？"
#message-radius-too-high: "&c错误:&7 范围不得高于 %d 个方块。"
#message-no-chests-nearby: "&7附近没有箱子，调整范围或靠近箱子一点。"
#message-error-not-a-number: "&c错误:&7 '%s' 不是一个有效的数字。"
#message-inventory-empty: "&7Nothing to unload: Your inventory is already empty."

##### Chinese (Traditional)
##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-could-not-unload: "&7沒有東西可以卸下，也許你沒有給其餘物品的箱子？"
#message-radius-too-high: "&c錯誤:&7 範圍不得高於 %d 個方塊。"
#message-no-chests-nearby: "&7附近沒有箱子，調整範圍或靠近箱子一點。"
#message-error-not-a-number: "&c錯誤:&7 '%s' 不是一個有效的數字。"
#message-inventory-empty: "&7Nothing to unload: Your inventory is already empty."

##### French
##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-could-not-unload: "&7Il n'y avait rien à décharger. Peut-être qu'il n'y a pas de coffres pour les objets restants?"
#message-radius-too-high: "&cErreur:&7 Le rayon ne peut pas être plus grand que &d blocs."
#message-no-chests-nearby: "&7Il n'y a aucun coffres à proximité. Ajustez le rayon ou approchez-vous de vos coffres."
#message-error-not-a-number: "&cErreur:&7 '%s' n'est pas un nombre valide."
#message-inventory-empty: "&7Nothing to unload: Your inventory is already empty."

##### German
#message-could-not-unload: "&7Konnte nichts abladen: Hier sind keine Kisten für die verbleibenden Items."
#message-radius-too-high: "&cFehler:&7 Der Radius kann nicht größer als %d Blöcke sein."
#message-no-chests-nearby: "&7Konnte nichts abladen: Keine Kisten in Reichweite. Ändere den Radius oder näher dich deinen Kisten."
#message-error-not-a-number: "&cFehler:&7 '%s' ist keine gültige Zahl."
#message-inventory-empty: "&7Konnte nichts abladen: Dein Inventar ist bereits leer."

##### Japanese
##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-could-not-unload: "&7荷物が下ろせません。目印になるアイテムがチェストにありますか？"
#message-radius-too-high: "&cError:&7 半径は %d個のブロックより大きくすることは出来ません。"
#message-no-chests-nearby: "&7近くにチェストがありません。半径を調整するかチェストに近づいて下さい。"
#message-error-not-a-number: "&cError:&7 '%s'は有効な数字ではありません。"
#message-inventory-empty: "&7Nothing to unload: Your inventory is already empty."

##### Spanish
#message-could-not-unload: "&7Nada que descargar: No hay cofres para los artículos restantes."
#message-radius-too-high: "&cError:&7 El radio no puede ser mayor a %d bloques."
#message-no-chests-nearby: "&7Nada que descargar: No hay cofres cerca. Ajusta el radio o ponte más cerca de tus cofres."
#message-error-not-a-number: "&cError:&7 '%s no es un número válido."
#message-inventory-empty: "&7Nada que descargar: Tu inventario ya está vacío."

#########################
#####     Done!     #####
#########################

# Enable for debug mode (you don't want this!)
debug: false

# please do not change the following line manually!
config-version: 17
